main: cc.altoya.settlements.App
name: settlements
version: 1
folia-supported: true
api-version: 1.20
description: Settlements plugin

commands:
  chunk:
    description: Claiming chunks
    usage: /chunk {var} {var}
  settlement:
    description: Settlements
    usage: /settlement {var} {var}