main: cc.altoya.settlements.App
name: settlements
version: 1
api-version: 1.21.1
description: Settlements plugin

commands:
  domain:
    description: Domains
    usage: /domain {var} {var}
  alliance:
    description: Alliances
    usage: /alliance {var} {var}
  structure:
    description: Structure
    usage: /structure {var} {var}