main: cc.altoya.settlements.App
name: settlements
version: 1.1
api-version: 1.21.1
description: Settlements plugin

commands:
  domain:
    description: Domains
    usage: /domain {subcommand} {var}
    tab-completer: cc.altoya.settlements.Domain.DomainTabCompleter

  alliance:
    description: Alliances
    usage: /alliance {subcommand} {var}
    tab-completer: cc.altoya.settlements.Alliance.AllianceTabCompleter
  build:
    description: Build
    usage: /build {subcommand} {var}
    tab-completer: cc.altoya.settlements.Build.BuildTabCompleter
  blueprint:
    description: Blueprint
    usage: /blueprint {subcommand} {var}
    tab-completer: cc.altoya.settlements.Blueprint.BlueprintTabCompleter